"""下载 RIFE ONNX 模型的指引脚本"""
print("=" * 60)
print("RIFE ONNX 模型下载")
print("=" * 60)
print()
print("请手动下载以下文件:")
print()
print("  1. 访问:")
print("     https://github.com/AmusementClub/vs-mlrt/releases/tag/model-20220923")
print()
print("  2. 下载 rife_v8.7z")
print()
print("  3. 解压后复制 rife-v4.6/rife_v4.6.onnx → models/rife/rife-v4.6/rife_v4.6.onnx")
print()
print("目录结构:")
print("  models/rife/rife-v4.6/")
print("  ├── rife_v4.6.onnx    (模型文件, ~30MB)")
print("  └── README.txt        (本说明)")
print()
print("首次运行 RTX_VSR_Tool 时会自动将 ONNX 编译为 TensorRT engine")
print("并缓存到 models/rife/rife-v4.6/rife_v4.6.onnx.engine")
print("=" * 60)
